menu/urls.py
from django.urls import path
from .views import (
    get_pdf,
    new_menu,
    menu_detail_by_date,
    menu_detail_by_pk,
    MenuListView,
    MenuUpdateView,
    MenuDeleteView,
    # change_published_status
)

app_name = "menu"

urlpatterns = [
    path("lista/", MenuListView.as_view(), name="list"),
    path("data/", menu_detail_by_date, name="date-detail"),
    path("<int:pk>/", menu_detail_by_pk, name="detail"),
    # path("<int:pk>/", MenuDetailView.as_view(), name="detail"),
    path("nowy/", new_menu, name="create"),
    path("edytuj/<int:pk>/", MenuUpdateView.as_view(), name="update"),
    path("usun/<int:pk>/", MenuDeleteView.as_view(), name="delete"),
    # path("publikacja/<int:pk>/", change_published_status, name="publish"),
    path("pdf/<int:pk>/", get_pdf, name="pdf"),
]

zawada/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path("menu/", include("menu.urls")),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += path("__reload__/", include("django_browser_reload.urls")),

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

menu/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_prose_editor.fields import ProseEditorField


class Menu(models.Model):

    date_from = models.DateField(_("From"))
    date_to = models.DateField(_("To"))
    published = models.BooleanField(_("Published"), default=False)
    breakfast1 = ProseEditorField(
        _("Breakfast on Monday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    breakfast2 = ProseEditorField(
        _("Breakfast on Tuesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    breakfast3 = ProseEditorField(
        _("Breakfast on Wednesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    breakfast4 = ProseEditorField(
        _("Breakfast on Thursday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    breakfast5 = ProseEditorField(
        _("Breakfast on Friday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    snack1 = ProseEditorField(
        _("Snack on Monday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    snack2 = ProseEditorField(
        _("Snack on Tuesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    snack3 = ProseEditorField(
        _("Snack on Wednesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    snack4 = ProseEditorField(
        _("Snack on Thursday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    snack5 = ProseEditorField(
        _("Snack on Friday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    soup1 = ProseEditorField(
        _("Soup on Monday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    soup2 = ProseEditorField(
        _("Soup on Tuesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    soup3 = ProseEditorField(
        _("Soup on Wednesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    soup4 = ProseEditorField(
        _("Soup on Thursday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    soup5 = ProseEditorField(
        _("Soup on Friday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    main1 = ProseEditorField(
        _("Main on Monday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    main2 = ProseEditorField(
        _("Main on Tuesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    main3 = ProseEditorField(
        _("Main on Wednesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    main4 = ProseEditorField(
        _("Main on Thursday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    main5 = ProseEditorField(
        _("Main on Friday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    dessert1 = ProseEditorField(
        _("Dessert on Monday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    dessert2 = ProseEditorField(
        _("Dessert on Tuesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    dessert3 = ProseEditorField(
        _("Dessert on Wednesday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    dessert4 = ProseEditorField(
        _("Dessert on Thursday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )
    dessert5 = ProseEditorField(
        _("Dessert on Friday"),
        null=True,
        blank=True,
        config={
            "types": [
                "strong",
            ],
            "history": True,
        },
    )

    def __str__(self):
        return f"Menu {self.date_from} - {self.date_to}"

    class Meta:
        ordering = ["-date_from"]

menu/forms.py
from django.forms import ModelForm, DateField, DateInput
from .models import Menu


class MenuForm(ModelForm):

    date_from = DateField(
        widget=DateInput(
            attrs={
                "type": "date",
                "class": "mx-2 px-2 py-1 rounded-md border-2 \
                      border-slate-200 ",
            },
            format="%Y-%m-%d",
        ),
        label="From",
    )
    date_to = DateField(
        widget=DateInput(
            attrs={
                "type": "date",
                "class": "flex items-center mx-2 px-2 py-1 rounded-md  \
                    border-2 border-slate-200 ",
            },
            format="%Y-%m-%d",
        ),
        label="To",
    )

    class Meta:
        model = Menu
        fields = "__all__"

menu/views.py
from datetime import datetime
from io import BytesIO
from django import forms
from django.http import FileResponse, HttpResponse
from django_htmx.http import trigger_client_event
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (
    DeleteView,
    ListView,
    UpdateView,
)
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table

from .filters import BaseFilter
from .forms import MenuForm
from .models import Menu
from .utils.pdf_styles import get_styles, linebreak


class MenuListView(ListView):
    model = Menu
    template_name = "menu/menu_list.html"
    context_object_name = "menu_list"

    def get_queryset(self):
        self.filterset = BaseFilter(
            self.request.GET, queryset=super().get_queryset()
            )
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.filterset
        context["menu_page"] = "active"
        return context


def menu_detail_by_pk(request, pk):
    """Menu detail view."""
    menu = get_object_or_404(Menu, pk=pk)

    next_menu = (
        Menu.objects.filter(
            date_from__gt=menu.date_from
            ).order_by("date_from").first()
    )
    prev_menu = Menu.objects.filter(date_from__lt=menu.date_from).first()

    context = {
        "menu": menu, "next": next_menu, "prev": prev_menu, "menu_page": "active"
        }

    # if request.htmx:
    #     return render(request, "menu/partials/menu_detail_partial.html", context)
    return render(request, "menu/menu_detail.html", context)


def menu_detail_by_date(request):
    """Menu detail view."""
    context = {}
    try:
        submitted_date = forms.DateField().clean(request.GET.get("selected_date"))
        selected_date = datetime.strftime(submitted_date, "%Y-%m-%d")
        menu = (
            Menu.objects.filter(date_from__lte=selected_date)
            .filter(date_to__gte=selected_date)
            .last()
        )
        if menu:
            next_menu = (
                Menu.objects.filter(date_from__gt=menu.date_from)
                .order_by("date_from")
                .first()
            )
            prev_menu = Menu.objects.filter(date_from__lt=menu.date_from).first()
            context.update({"next": next_menu, "prev": prev_menu})

    except forms.ValidationError:
        menu = None

    context["menu"] = menu
    context["menu_page"] = "active"


    # if request.htmx:
    #     return render(request, "menu/partials/menu_detail_partial.html", context)
    return render(request, "menu/menu_detail.html", context)


def new_menu(request):
    form = MenuForm()
    context = {}
    context["form"] = form
    context["creating"] = True
    context["menu_page"] = "active"

    if request.method == "POST":
        form = MenuForm(request.POST)
        if form.is_valid():
            new_menu = form.save()
            return render(request, "menu/menu_detail.html", {"menu": new_menu})
    return render(request, "menu/menu_form.html", context)


class MenuUpdateView(UpdateView):
    """Menu update view."""

    model = Menu
    form_class = MenuForm
    template_name = "menu/menu_form.html"
    success_url = reverse_lazy("menu:list")
    context_object_name = "menu"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu_page"] = "active"
        return context


class MenuDeleteView(DeleteView):
    model = Menu
    success_url = reverse_lazy("menu:list")  # unused in HTMX case

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        # Send a 204 No Content response with an HX-Trigger header
        response = HttpResponse(status=204)
        response = trigger_client_event(response, "menuDeleted")
        return response


# def change_published_status(request, pk):
#     """Change published status of menu."""
#     menu = Menu.objects.get(pk=pk)
#     menu.published = not menu.published
#     menu.save()
#     response = HttpResponse(status=204)
#     response = trigger_client_event(response, 'menuChanged')
#     return response


def get_pdf(request, pk):

    menu = Menu.objects.get(id=pk)
    date_from = menu.date_from.strftime("%d.%m.")
    date_to = menu.date_to.strftime("%d.%m.%Y")

    pdf_buffer = BytesIO()

    normalStyle, headingStyle, style, style_table = get_styles()

    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=landscape(A4),
        rightMargin=25,
        leftMargin=25,
        topMargin=15,
        bottomMargin=15,
    )
    data = [
        [
            Paragraph("", headingStyle),
            Paragraph("Śniadanie", headingStyle),
            Paragraph("II Śniadanie", headingStyle),
            Paragraph("Zupa", headingStyle),
            Paragraph("II danie", headingStyle),
            Paragraph("Podwieczorek", headingStyle),
        ]
    ]

    monday = [
        Paragraph("Poniedziałek", normalStyle),
        Paragraph(linebreak(menu.breakfast1), normalStyle),
        Paragraph(linebreak(menu.snack1), normalStyle),
        Paragraph(linebreak(menu.soup1), normalStyle),
        Paragraph(linebreak(menu.main1), normalStyle),
        Paragraph(linebreak(menu.dessert1), normalStyle),
    ]
    tuesday = [
        Paragraph("Wtorek", normalStyle),
        Paragraph(linebreak(menu.breakfast2), normalStyle),
        Paragraph(linebreak(menu.snack2), normalStyle),
        Paragraph(linebreak(menu.soup2), normalStyle),
        Paragraph(linebreak(menu.main2), normalStyle),
        Paragraph(linebreak(menu.dessert2), normalStyle),
    ]
    wednesday = [
        Paragraph("Środa", normalStyle),
        Paragraph(linebreak(menu.breakfast3), normalStyle),
        Paragraph(linebreak(menu.snack3), normalStyle),
        Paragraph(linebreak(menu.soup3), normalStyle),
        Paragraph(linebreak(menu.main3), normalStyle),
        Paragraph(linebreak(menu.dessert3), normalStyle),
    ]
    thursday = [
        Paragraph("Czwartek", normalStyle),
        Paragraph(linebreak(menu.breakfast4), normalStyle),
        Paragraph(linebreak(menu.snack4), normalStyle),
        Paragraph(linebreak(menu.soup4), normalStyle),
        Paragraph(linebreak(menu.main4), normalStyle),
        Paragraph(linebreak(menu.dessert4), normalStyle),
    ]
    friday = [
        Paragraph("Piątek", normalStyle),
        Paragraph(linebreak(menu.breakfast5), normalStyle),
        Paragraph(linebreak(menu.snack5), normalStyle),
        Paragraph(linebreak(menu.soup5), normalStyle),
        Paragraph(linebreak(menu.main5), normalStyle),
        Paragraph(linebreak(menu.dessert5), normalStyle),
    ]
    data.append(monday)
    data.append(tuesday)
    data.append(wednesday)
    data.append(thursday)
    data.append(friday)

    table = Table(
        data,
        spaceBefore=20,
        colWidths=[30 * mm, 55 * mm, 35 * mm, 45 * mm, 55 * mm, 50 * mm],
        minRowHeights=[5 * mm, 20 * mm, 20 * mm, 20 * mm, 20 * mm, 20 * mm],
    )

    elems = []
    elems.append(Paragraph((f"Jadłospis od {date_from} do {date_to}"), style=style))
    elems.append(Spacer(1, 6))
    elems.append(table)

    table.setStyle(style_table)

    doc.build(elems)
    pdf_buffer.seek(0)
    return FileResponse(
        pdf_buffer, as_attachment=False, filename=f"Jadlospis_{menu.date_from}.pdf"
    )

zawada/templates/menu/partials/menu_detail_partial.html
{% load static wagtailcore_tags i18n %}
<div id="menu-detail">
  <title id="pageTitle" hx-swap-oob="true">Jadłospis</title>
  <div
    id="spinner"
    class="request-indicator htmx-indicator absolute inset-0 z-30 min-h-dvh w-full bg-neutral-200"
  >
    <div
      class="loader-circle absolute top-1/2 left-1/2 z-30 -translate-x-1/2"
    ></div>
  </div>
  <main
    class="mx-auto max-w-[1200px] px-2 pt-2 pb-10"
    hx-get="{% url 'menu:list' %}"
    hx-trigger="menuDeleted from:body"
    hx-swap="outerHTML"
  >
    <div class="flex flex-wrap items-center gap-3">
      <a
        href="{% url 'menu:list' %}"
        hx-get="{% url 'menu:list' %}"
        hx-target="#menu-detail"
        hx-swap="outerHTML"
        hx-select="#main-menu"
        hx-push-url="true"
        class="my-1 flex max-w-max cursor-pointer items-center justify-center gap-2 rounded-full
        border-2 border-[#d3af37] bg-gray-50 px-4 py-2 font-semibold uppercase transition-all duration-300
        hover:bg-[#d4bf79] hover:ring-2 hover:ring-[#d3af37] hover:ring-offset-2"
        type="submit"
      >
        <svg class="h-4 w-4 fill-neutral-800" alt="" aria-hidden="true">
          <use href="{% static 'img/sprite.svg' %}#list" />
        </svg>
        Lista
      </a>
      {% if menu %}
      <a
        href="{% url 'menu:update' menu.id %}"
        hx-get="{% url 'menu:update' menu.id %}"
        hx-target="#menu-detail"
        hx-swap="outerHTML"
        hx-select="#menu-form"
        hx-push-url="true"
        hx-indicator="#spinner, .loaded-content"
        class="my-1 flex max-w-max cursor-pointer items-center justify-center gap-2 rounded-full
        border-2 border-[#d3af37] bg-gray-50 px-4 py-2 font-semibold uppercase transition-all duration-300
        hover:bg-[#d4bf79] hover:ring-2 hover:ring-[#d3af37] hover:ring-offset-2"
        type="submit"
      >
        <svg class="h-4 w-4 fill-neutral-800" alt="" aria-hidden="true">
          <use href="{% static 'img/sprite.svg' %}#pencil" />
        </svg>
        Edytuj
      </a>
      <a
        class="my-1 flex max-w-max cursor-pointer items-center justify-center gap-2 rounded-full
        border-2 border-[#d3af37] bg-gray-50 px-4 py-2 font-semibold uppercase transition-all
        duration-300 hover:bg-[#d4bf79] hover:ring-2 hover:ring-[#d3af37] hover:ring-offset-2"
        hx-delete="{% url 'menu:delete' menu.id %}"
        hx-target="#menu-detail"
        hx-swap="outerHTML"
        confirm-swal="jadłospis od {{ menu.date_from|date:'d.m.' }} do {{ menu.date_to|date:'d.m.Y' }}"
      >
        <svg class="h-4 w-4 fill-neutral-800" alt="" aria-hidden="true">
          <use href="{% static 'img/sprite.svg' %}#trash" />
        </svg>
        Usuń
      </a>
      <a
        href="{% url 'menu:pdf' menu.id %}"
        class="my-1 flex max-w-max cursor-pointer items-center justify-center gap-2 rounded-full border-2 border-[#d3af37]
        bg-gray-50 px-4 py-2 font-semibold uppercase transition-all duration-300 hover:bg-[#d4bf79] hover:ring-2 hover:ring-[#d3af37] hover:ring-offset-2"
      >
        <svg class="h-4 w-4 fill-neutral-800" alt="" aria-hidden="true">
          <use href="{% static 'img/sprite.svg' %}#download" />
        </svg>
        PDF
      </a>
      {% endif %}
    </div>
    <div class="flex flex-wrap items-center justify-between gap-2">
      {% if menu %}
      <div class="flex flex-wrap items-center justify-start gap-4">
        <h1
          class="my-4 text-center text-3xl font-bold text-teal-950 md:my-6 lg:my-10"
        >
          Jadłospis od {{menu.date_from|date:"d.m."}} do {{menu.date_to|date:"d.m.Y"}}
        </h1>
      </div>
      {% else %}
      <h1 class="mt-8 mb-10 text-3xl font-bold text-teal-950">
        Brak jadłospisu w wybranym okresie
      </h1>
      {% endif %}
      <form
        method="get"
        action='{% url "menu:date-detail" %}'
        hx-get='{% url "menu:date-detail" %}'
        hx-target="#menu-detail"
        hx-select="#menu-detail"
        hx-push-url="true"
        hx-swap="outerHTML"
        autocomplete="off"
        class="mx-2 my-4 flex items-center justify-center gap-2"
      >
        <label for="datepicker" class="font-semibold">Przejdź do:</label>
        <div class="relative max-w-sm">
          <div
            class="pointer-events-none absolute inset-y-0 start-0 flex items-center ps-3.5"
          >
            <svg
              class="h-4 w-4 text-gray-500 dark:text-gray-400"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              viewBox="0 0 20 20"
            >
              <path
                d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"
              />
            </svg>
          </div>
          <input
            datepicker
            id="datepicker"
            type="text"
            name="selected_date"
            class="block w-full rounded-l-lg border border-gray-300 bg-gray-50 p-2.5 ps-10 text-sm
            text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600
            dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
            placeholder="Wybierz datę"
          />
        </div>
        <button
          class="my-1 -ml-2 max-w-max cursor-pointer rounded-r-lg bg-[#d3af37] px-4 py-2
          font-semibold uppercase transition-all duration-300 hover:ring-2 hover:ring-[#d3af37] hover:ring-offset-2"
          type="submit"
        >
          OK
        </button>
      </form>
    </div>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <table
        class="w-full text-left text-gray-700 rtl:text-right dark:text-gray-400"
      >
        <thead
          class="bg-teal-700 text-sm text-white uppercase dark:bg-gray-700 dark:text-gray-400"
        >
          <tr>
            <th scope="col" class="px-4 py-3">
              <span class="sr-only">Dzień</span>
            </th>
            <th scope="col" class="px-4 py-3">Śniadanie</th>
            <th scope="col" class="px-4 py-3">II&nbsp;śniadanie</th>
            <th scope="col" class="px-4 py-3">Zupa</th>
            <th scope="col" class="px-4 py-3">II danie</th>
            <th scope="col" class="px-4 py-3">Podwieczorek</th>
          </tr>
        </thead>
        <tbody>
          <tr
            class="border-b border-gray-200 bg-white hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-600"
          >
            <th
              scope="row"
              class="px-4 py-4 font-medium whitespace-nowrap text-teal-900 dark:text-white"
            >
              Poniedziałek
            </th>
            <td class="px-4 py-4">{{ menu.breakfast1|richtext }}</td>
            <td class="px-4 py-4">{{ menu.snack1|richtext }}</td>
            <td class="px-4 py-4">{{ menu.soup1|richtext }}</td>
            <td class="px-4 py-4">{{ menu.main1|richtext }}</td>
            <td class="px-4 py-4">{{ menu.dessert1|richtext }}</td>
          </tr>
          <tr
            class="border-b border-gray-200 bg-white hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-600"
          >
            <th
              scope="row"
              class="px-4 py-4 font-medium whitespace-nowrap text-teal-900 dark:text-white"
            >
              Wtorek
            </th>
            <td class="px-4 py-4">{{ menu.breakfast2|richtext }}</td>
            <td class="px-4 py-4">{{ menu.snack2|richtext }}</td>
            <td class="px-4 py-4">{{ menu.soup2|richtext }}</td>
            <td class="px-4 py-4">{{ menu.main2|richtext }}</td>
            <td class="px-4 py-4">{{ menu.dessert2|richtext }}</td>
          </tr>
          <tr
            class="border-b border-gray-200 bg-white hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-600"
          >
            <th
              scope="row"
              class="px-4 py-4 font-medium whitespace-nowrap text-teal-900 dark:text-white"
            >
              Środa
            </th>
            <td class="px-4 py-4">{{ menu.breakfast3|richtext }}</td>
            <td class="px-4 py-4">{{ menu.snack3|richtext }}</td>
            <td class="px-4 py-4">{{ menu.soup3|richtext }}</td>
            <td class="px-4 py-4">{{ menu.main3|richtext }}</td>
            <td class="px-4 py-4">{{ menu.dessert3|richtext }}</td>
          </tr>
          <tr
            class="border-b border-gray-200 bg-white hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-600"
          >
            <th
              scope="row"
              class="px-4 py-4 font-medium whitespace-nowrap text-teal-900 dark:text-white"
            >
              Czwartek
            </th>
            <td class="px-4 py-4">{{ menu.breakfast4|richtext }}</td>
            <td class="px-4 py-4">{{ menu.snack4|richtext }}</td>
            <td class="px-4 py-4">{{ menu.soup4|richtext }}</td>
            <td class="px-4 py-4">{{ menu.main4|richtext }}</td>
            <td class="px-4 py-4">{{ menu.dessert4|richtext }}</td>
          </tr>
          <tr
            class="border-b border-gray-200 bg-white hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-600"
          >
            <th
              scope="row"
              class="px-4 py-4 font-medium whitespace-nowrap text-teal-900 dark:text-white"
            >
              Piątek
            </th>
            <td class="px-4 py-4">{{ menu.breakfast5|richtext }}</td>
            <td class="px-4 py-4">{{ menu.snack5|richtext }}</td>
            <td class="px-4 py-4">{{ menu.soup5|richtext }}</td>
            <td class="px-4 py-4">{{ menu.main5|richtext }}</td>
            <td class="px-4 py-4">{{ menu.dessert5|richtext }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="mt-3 flex w-full flex-wrap items-center justify-center gap-4">
      {% if prev %}
      <a
        href="{% url 'menu:detail' prev.id %}"
        class="flex items-center gap-2 font-semibold text-teal-800 underline underline-offset-2 hover:no-underline"
      >
        <svg class="-mb-1 h-4 w-4 fill-teal-800" alt="" aria-hidden="true">
          <use href="{% static 'img/sprite.svg' %}#arrow-left" /></svg
        >Poprzedni</a
      >
      {% endif %}
      {% if next %}
      <a
        href="{% url 'menu:detail' next.id %}"
        class="flex items-center gap-2 font-semibold text-teal-800 underline underline-offset-2 hover:no-underline"
        >Następny
        <svg
          class="-mb-1 h-4 w-4 rotate-180 fill-teal-800"
          alt=""
          aria-hidden="true"
        >
          <use href="{% static 'img/sprite.svg' %}#arrow-left" />
        </svg>
      </a>
      {% endif %}
    </div>
  </main>
</div>